#ifndef CMT_MACROS_HPP
#define CMT_MACROS_HPP

#include <boost/config.hpp>
#define CMT_SYMBOL_VISIBLE BOOST_SYMBOL_VISIBLE
#define CMT_SYMBOL_EXPORT BOOST_SYMBOL_EXPORT
#define CMT_SYMBOL_IMPORT BOOST_SYMBOL_IMPORT

#endif
